import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { FcGoogle } from "react-icons/fc"
import { getAuth, signInWithPopup,GoogleAuthProvider } from "firebase/auth"
import { app } from "../config/Firebase"
import { useRouter } from "next/router"
export default function Home() {
  

    const auth = getAuth(app)
    const provider = new GoogleAuthProvider()
    const router = useRouter()
    const signin = async()=>{
      const { user } = await signInWithPopup(auth,provider)
      const { refreshToken, providerData } = user
      localStorage.setItem("user",JSON.stringify(providerData))
      localStorage.setItem("access",JSON.stringify(refreshToken))
      router.push("/Todo")
    }
  
    
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-red-300 flex justify-center items-center w-screen h-screen fixed '>
        <div className='bg-gray-300 w-100 h-100 px-10 py-5 rounded-xl flex items-center gap-5 font-bold hover:scale-105 hover:text-blue-500 hover:shadow-xl duration-300 cursor-pointer' onClick={signin}>
          <FcGoogle fontSize={30}/>
          Sign in with Google
        </div>
      </div>
      
    </div>
  )
}
